[2023-03-29T14:26:41.991+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.extract_and_load scheduled__2023-03-29T13:55:00+00:00 [queued]>
[2023-03-29T14:26:42.156+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.extract_and_load scheduled__2023-03-29T13:55:00+00:00 [queued]>
[2023-03-29T14:26:42.159+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T14:26:42.162+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T14:26:42.165+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T14:26:42.346+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_and_load> on 2023-03-29 13:55:00+00:00
[2023-03-29T14:26:42.761+0000] {standard_task_runner.py:55} INFO - Started process 2581 to run task
[2023-03-29T14:26:43.044+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'extract_and_load', 'scheduled__2023-03-29T13:55:00+00:00', '--job-id', '401', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpo69dvnje']
[2023-03-29T14:26:43.262+0000] {standard_task_runner.py:83} INFO - Job 401: Subtask extract_and_load
[2023-03-29T14:26:47.964+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.extract_and_load scheduled__2023-03-29T13:55:00+00:00 [running]> on host e7ec0deaf382
[2023-03-29T14:26:52.137+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=extract_and_load
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T13:55:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T13:55:00+00:00
[2023-03-29T14:26:52.161+0000] {logging_mixin.py:137} INFO - eeeee test-chronotruck test-chr-ml/primary/data.csv
[2023-03-29T14:45:12.278+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-03-29T14:45:12.591+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 2581. PIDs of all processes in the group: [2581]
[2023-03-29T14:45:12.601+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 2581
[2023-03-29T14:45:12.621+0000] {taskinstance.py:1482} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-03-29T14:45:14.395+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2581, status='terminated', exitcode=0, started='14:26:42') (2581) terminated with exit code 0
