[2023-03-29T01:41:36.646+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.load_predict scheduled__2023-03-29T01:05:00+00:00 [queued]>
[2023-03-29T01:41:36.742+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.load_predict scheduled__2023-03-29T01:05:00+00:00 [queued]>
[2023-03-29T01:41:36.747+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T01:41:36.750+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T01:41:36.751+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T01:41:36.826+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): load_predict> on 2023-03-29 01:05:00+00:00
[2023-03-29T01:41:36.943+0000] {standard_task_runner.py:55} INFO - Started process 1088 to run task
[2023-03-29T01:41:36.973+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'load_predict', 'scheduled__2023-03-29T01:05:00+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp8ei8k86t']
[2023-03-29T01:41:36.997+0000] {standard_task_runner.py:83} INFO - Job 290: Subtask load_predict
[2023-03-29T01:41:37.205+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.load_predict scheduled__2023-03-29T01:05:00+00:00 [running]> on host 18cf4662f3ac
[2023-03-29T01:41:39.400+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=load_predict
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T01:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T01:05:00+00:00
[2023-03-29T01:58:09.071+0000] {gbq.py:352} INFO -   Elapsed 10.44 s. Waiting...
[2023-03-29T01:58:11.739+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py:1988: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  create_bqstorage_client=create_bqstorage_client,

[2023-03-29T01:58:42.230+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to upstream_failed. Terminating instance.
[2023-03-29T01:58:42.358+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 1088. PIDs of all processes in the group: [1088]
[2023-03-29T01:58:42.377+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 1088
[2023-03-29T01:59:18.787+0000] {taskinstance.py:1482} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-03-29T01:59:18.827+0000] {logging_mixin.py:137} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7ff4dd7b8950>
[2023-03-29T01:59:18.829+0000] {logging_mixin.py:137} WARNING - Traceback (most recent call last):
[2023-03-29T01:59:18.831+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/weakref.py", line 358, in remove
[2023-03-29T01:59:18.835+0000] {logging_mixin.py:137} WARNING -     def remove(k, selfref=ref(self)):
[2023-03-29T01:59:18.837+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1483, in signal_handler
[2023-03-29T01:59:18.862+0000] {logging_mixin.py:137} WARNING -     raise AirflowTermSignal("Task received SIGTERM signal")
[2023-03-29T01:59:18.864+0000] {logging_mixin.py:137} WARNING - ***.exceptions.AirflowTermSignal: Task received SIGTERM signal
[2023-03-29T01:59:42.941+0000] {process_utils.py:147} WARNING - process psutil.Process(pid=1088, name='airflow task ru', status='running', started='01:41:36') did not respond to SIGTERM. Trying SIGKILL
[2023-03-29T01:59:44.747+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 1088
[2023-03-29T01:59:58.125+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1088, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='01:41:36') (1088) terminated with exit code Negsignal.SIGKILL
[2023-03-29T01:59:59.397+0000] {standard_task_runner.py:170} ERROR - Job 290 was killed before it finished (likely due to running out of memory)
